### ISSUE TITLE
Unparalleled Finesse and Cycle of Violence don't combo.

### ISSUE THREAD

**Issue by hollandra** [Corgwn/STS_Highwayman_Mod#8]
The intended functionality is that these together should blunt multi attacks: the first attack that breaks through your block should give you riposte and therefore block for the next hit. Currently, all the block is given after the entire multi attack finishes, and then it is immediately lost at the start of your turn.

**Comment by Corgwn** [comment]
This should be as simple as adding the block gain to the top of the stack instead of the bottom
